name: open_settings_plus
description: The most complete flutter plugin packages for open various settings screen, covering newer versions of ios and android.
version: 0.3.3
homepage: https://github.com/yanncabral/open_settings_plus

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.yanncabral.open_settings_plus
        pluginClass: OpenSettingsPlusPlugin
      ios:
        pluginClass: OpenSettingsPlusPlugin
